### ISSUE TITLE
Менять порядок комнат

### ISSUE THREAD

**Issue by SpeedFire0** [sprut/Home#100]
Либо этого нет, либо это не очень очевидно как можно настроить.
Хотелось бы:
1) Чтобы комнаты были в том же порядке что и в приложении Дом
2) Возможность менять порядок в самом Спрут Хоум

**Comment by sprut666666** [comment]
1) Это невозможно, эпл не отдаёт порядок
2) Слева сверху нажать на название дома - настройки - комнаты
