### ISSUE TITLE
Потребление энергии из Home Assistant

### ISSUE THREAD

**Issue by SpeedFire0** [sprut/Home#101]
Можно ли как-то просто прокинуть данные из Home Assistant (там собираются данные по потреблению умных розеток Xiaomi).

Хотелось бы, чтобы автоматически собирались данные по сенсорам с параметром:
unit_of_measurement: 'kWh' 
unit_of_measurement: 'Wh'

**configuration.yaml**
**Сбор данных о потреблении энергии с умных розеток**
utility_meter:
  gostinaya_consumption_daily:
    name: Гостиная дневное
    source: sensor.gostinaya_consumption
    cycle: daily

**Прокидывание данных в HomeKit**
sensor:
  - platform: template
    sensors:
       **Прокидывание данных в HomeKit в виде сенсора освещенности**
       home_energy_usage:
         friendly_name: Обогреватели
         unit_of_measurement: 'lx'
         device_class: power
         value_template: "{{(states('sensor.gostinaya_consumption_daily') | float  + states('sensor.kabinet_consumption_daily') | float  + states('sensor.spalna_consumption_daily') | float ) / 1000}}"
       **А ВОТ ТАК ХОТЕЛОСЬ БЫ ПРОКИДЫВАТЬ В SPRUT HOME:**
     home_energy_usage_kw:
         friendly_name: Обогреватели кВт
         unit_of_measurement: 'kWh'
         device_class: power
         value_template: "{{(states('sensor.gostinaya_consumption_daily') | float  + states('sensor.kabinet_consumption_daily') | float  + states('sensor.spalna_consumption_daily') | float ) / 1000}}"

**Comment by sprut666666** [comment]
Для этого нужно в хомкит передать: новый сервис и характеристику
C_WattMeter(
		"00000010-6666-6666-6666-666666666666", //
		l(C_Watt.class), // Required
		l(Name.class) // Optional
),
C_Watt("00000016-6666-6666-6666-666666666666", true, false, true, "float", 0f, 65535f, 1.0f, null, "W", null),
и
C_KilowattHourMeter(
		"00000012-6666-6666-6666-666666666666", //
		l(C_KilowattHour.class), // Required
		l(Name.class) // Optional
),
C_KilowattHour("00000018-6666-6666-6666-666666666666", true, false, true, "float", 0f, 65535f, 1.0f, null, "kWh", null),
Тогда всё будет работать
