### ISSUE TITLE
При открывании комнаты с камерой отображение микрофона в процентах съезжает влево и становится не видно, съезжает вся строка.

### ISSUE THREAD

**Issue by shurikshurikov** [sprut/Home#12]
![image](https://user-images.githubusercontent.com/59749751/96387179-d6bfbd00-11a8-11eb-9c7b-27ca14844e82.jpeg)

Версия iOS 14.0.1
iPhone 6S

** Подробное описание ошибки **
Чётко и коротко об ошибке.

** Как воспроизвести ? **
Шаги для воспроизведения ошибки, описывать как для "тупых" максимально подробно:
1. Перейдите к «...»
2. Нажмите «....»
3. Прокрутите вниз до «....»
4. Смотрите ошибку

** Ожидаемое поведение **
Четкое и краткое описание того, что вы ожидали.

** Скриншоты/ Логи **
Приложите скриншоты или логи, для описания проблемы.

** Пожалуйста, заполните следующую информацию: **
  - Версия: [например, IOS]

** Дополнительные материалы **
Приложите дополнительные материалы помогающие раскрыть проблему: ссылки, скриншоты и т.д.

**Comment by Bigmanekb** [comment]
![iPad Pro 13 2018](https://user-images.githubusercontent.com/46221443/96387226-ed224480-11b9-11eb-8493-c105cf3fea4f.jpg)
