### ISSUE TITLE
Двойное отображение влажности

### ISSUE THREAD

**Issue by LowriderA** [sprut/Home#5]
** Подробное описание ошибки **
В комнате влажность отображается двумя цифрами через дефис. 65-65%. В комнате только один датчик. 

** Как воспроизвести ? **
Датчик влажности xiaomi или aqara (других нет). Прокинуты в ХА через родной шлюз. С ХА в Дом. 
Если Показания датчика в ХА и МиХоме не целое число (например 65,1%) то в Приложении показатель будет задвоен. Если Показания - целое число, то в приложении все ок. 

** Ожидаемое поведение **
Скорее всего нужно добавить отображение влажности с десятой. 

** Скриншоты/ Логи **

![80D0F70D-2F3F-4ED1-81BD-01306BB019B6](https://user-images.githubusercontent.com/41893088/71742457-84f0b500-2e6a-11ea-84c1-c7a47a9421b3.png)
![0A3B4E39-FD34-44A4-8DFC-B8524D0B1393](https://user-images.githubusercontent.com/41893088/71742486-9f2a9300-2e6a-11ea-913c-269f836a5647.png)

** Пожалуйста, заполните следующую информацию: **
  - Версия: 13.3 iPhone X

**Comment by olddeda** [comment]
Поправил. Нужно проверить
