### ISSUE TITLE
Пункт меню "Настройки" малозаметен

### ISSUE THREAD

**Issue by andreypopov** [sprut/Home#6]
** Максимально подробное описание предложения.**
Текст "Настройки" , в меню,  слишком тусклый, я его не видел, пока не спросил, где эти настройки. Может быть чуть заметнее сделать.

** Дополнительные материалы **
![photo_2020-01-05_19-25-11](https://user-images.githubusercontent.com/1624839/71784739-d84c3a00-3007-11ea-9e96-82b7954a6fdd.jpg)
![photo_2020-01-05_19-25-07](https://user-images.githubusercontent.com/1624839/71784740-d84c3a00-3007-11ea-866a-e377af3f77dd.jpg)
![photo_2020-01-05_19-24-55](https://user-images.githubusercontent.com/1624839/71784741-d8e4d080-3007-11ea-8775-6220770eebcb.jpg)

**Comment by olddeda** [comment]
Сделал заметнее
