### ISSUE TITLE
Окно - неправильный статус,  не работает с инверсией

### ISSUE THREAD

**Issue by andreypopov** [sprut/Home#7]
в СХ окно с инверсией, замечены следующие ошибки
1) при закрытии окна в ХК пишет closing, в спрут хоум - Открытие и наоборот
2) после полного закрытия окна, статус становится "Открытие"

![IMG_3707](https://user-images.githubusercontent.com/1624839/72242207-e0a10800-35f9-11ea-8edf-a6113a5150f2.PNG)

**Comment by olddeda** [comment]
Нужно проверить
