### ISSUE TITLE
Переход в комнаты и устройства из окна "дайджеста" 

### ISSUE THREAD

**Issue by permadm** [sprut/Home#79]
![C62FBDE2-B7DE-4FA6-B1D0-BCAC18C4667E](https://user-images.githubusercontent.com/23650010/101274733-4eca5c80-37c2-11eb-9561-7898d6a79342.png)
Предложение: при тапе (или длинном тапе): 
1. на название комнаты - переходить в эту комнату; 
2. на названии устройства - переходить в это устройство

**Comment by olddeda** [comment]
Это излишне
